import 'package:flutter/material.dart';
import 'album.dart';
var photoPath_taitungLibrary = [ 
"albums/taitungLibrary/DSCF5104.JPG",
"albums/taitungLibrary/DSCF5112.JPG",
"albums/taitungLibrary/DSCF5113.JPG",
"albums/taitungLibrary/DSCF5114.JPG",
"albums/taitungLibrary/DSCF5115.JPG",
"albums/taitungLibrary/DSCF5116.JPG",
"albums/taitungLibrary/DSCF5118.JPG",
"albums/taitungLibrary/DSCF5122.JPG",
"albums/taitungLibrary/DSCF5126.JPG",
"albums/taitungLibrary/DSCF5127.JPG",
"albums/taitungLibrary/DSCF5128.JPG",
"albums/taitungLibrary/DSCF5129.JPG",
"albums/taitungLibrary/DSCF5133.JPG",
"albums/taitungLibrary/DSCF5134.JPG",
"albums/taitungLibrary/DSCF5135.JPG",
"albums/taitungLibrary/DSCF5137.JPG",
];
var photoFullPath_taitungLibrary = [ 
"albums/taitungLibrary/full/DSCF5104.JPG",
"albums/taitungLibrary/full/DSCF5112.JPG",
"albums/taitungLibrary/full/DSCF5113.JPG",
"albums/taitungLibrary/full/DSCF5114.JPG",
"albums/taitungLibrary/full/DSCF5115.JPG",
"albums/taitungLibrary/full/DSCF5116.JPG",
"albums/taitungLibrary/full/DSCF5118.JPG",
"albums/taitungLibrary/full/DSCF5122.JPG",
"albums/taitungLibrary/full/DSCF5126.JPG",
"albums/taitungLibrary/full/DSCF5127.JPG",
"albums/taitungLibrary/full/DSCF5128.JPG",
"albums/taitungLibrary/full/DSCF5129.JPG",
"albums/taitungLibrary/full/DSCF5133.JPG",
"albums/taitungLibrary/full/DSCF5134.JPG",
"albums/taitungLibrary/full/DSCF5135.JPG",
"albums/taitungLibrary/full/DSCF5137.JPG",
];
var info_taitungLibrary = [ 
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
];
Album taitungLibrary = Album(photoPath_taitungLibrary, photoFullPath_taitungLibrary, info_taitungLibrary, 'taitungLibrary', 'taitungLibrary', 'taitungLibrary', 'taitungLibrary');
