import 'package:flutter/material.dart';
import 'album.dart';
var photoPath_ckshow = [ 
"albums/ckshow/_DSF0066.jpg",
"albums/ckshow/_DSF0166.jpg",
"albums/ckshow/_DSF0222.jpg",
"albums/ckshow/_DSF0224.jpg",
"albums/ckshow/_DSF0520.jpg",
"albums/ckshow/_DSF7782.jpg",
"albums/ckshow/_DSF7826.jpg",
"albums/ckshow/_DSF7832.jpg",
"albums/ckshow/_DSF7849.jpg",
"albums/ckshow/_DSF7892.jpg",
"albums/ckshow/_DSF8007.jpg",
"albums/ckshow/_DSF8240.jpg",
"albums/ckshow/_DSF8449.jpg",
"albums/ckshow/_DSF8611.jpg",
"albums/ckshow/_DSF8677.jpg",
"albums/ckshow/_DSF9049.jpg",
"albums/ckshow/_DSF9177.jpg",
"albums/ckshow/_DSF9313.jpg",
"albums/ckshow/_DSF9387.jpg",
"albums/ckshow/_DSF9464.jpg",
"albums/ckshow/_DSF9531.jpg",
"albums/ckshow/_DSF9550.jpg",
"albums/ckshow/_DSF9633.jpg",
"albums/ckshow/_DSF9806.jpg",
];
var photoFullPath_ckshow = [ 
"albums/ckshow/full/_DSF0066.jpg",
"albums/ckshow/full/_DSF0166.jpg",
"albums/ckshow/full/_DSF0222.jpg",
"albums/ckshow/full/_DSF0224.jpg",
"albums/ckshow/full/_DSF0520.jpg",
"albums/ckshow/full/_DSF7782.jpg",
"albums/ckshow/full/_DSF7826.jpg",
"albums/ckshow/full/_DSF7832.jpg",
"albums/ckshow/full/_DSF7849.jpg",
"albums/ckshow/full/_DSF7892.jpg",
"albums/ckshow/full/_DSF8007.jpg",
"albums/ckshow/full/_DSF8240.jpg",
"albums/ckshow/full/_DSF8449.jpg",
"albums/ckshow/full/_DSF8611.jpg",
"albums/ckshow/full/_DSF8677.jpg",
"albums/ckshow/full/_DSF9049.jpg",
"albums/ckshow/full/_DSF9177.jpg",
"albums/ckshow/full/_DSF9313.jpg",
"albums/ckshow/full/_DSF9387.jpg",
"albums/ckshow/full/_DSF9464.jpg",
"albums/ckshow/full/_DSF9531.jpg",
"albums/ckshow/full/_DSF9550.jpg",
"albums/ckshow/full/_DSF9633.jpg",
"albums/ckshow/full/_DSF9806.jpg",
];
var info_ckshow = [ 
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
];
Album ckshow = Album(photoPath_ckshow, photoFullPath_ckshow, info_ckshow, 'ckshow', 'ckshow', 'ckshow', 'ckshow');
