import 'package:flutter/material.dart';
import 'album.dart';

var photoPath_uk = [
  "albums/uk/DSCF5651.JPG",
  "albums/uk/DSCF5727.jpg",
  "albums/uk/DSCF5760.JPG",
  "albums/uk/DSCF6031.JPG",
  "albums/uk/DSCF6172.jpg",
  "albums/uk/DSCF6209.jpg",
  "albums/uk/DSCF6317.jpg",
  "albums/uk/DSCF6328.jpg",
  "albums/uk/DSCF6491.jpg",
  "albums/uk/DSCF6524.jpg",
  "albums/uk/DSCF6550.jpg",
  "albums/uk/DSCF6642.jpg",
  "albums/uk/DSCF6729.jpg",
  "albums/uk/DSCF6756.jpg",
  "albums/uk/DSCF6775.jpg",
  "albums/uk/DSCF6908.jpg",
  "albums/uk/DSCF6960.jpg",
  "albums/uk/DSCF7083.jpg",
  "albums/uk/DSCF7582.jpg",
  "albums/uk/DSCF8020.JPG",
  "albums/uk/DSCF8039.JPG",
  "albums/uk/DSCF8056.jpg",
  "albums/uk/DSCF8312.JPG",
  "albums/uk/DSCF8514.JPG",
  "albums/uk/DSCF8687.JPG",
  "albums/uk/DSCF8826.jpg",
];
var photoFullPath_uk = [
  "albums/uk/full/DSCF5651.JPG",
  "albums/uk/full/DSCF5727.jpg",
  "albums/uk/full/DSCF5760.JPG",
  "albums/uk/full/DSCF6031.JPG",
  "albums/uk/full/DSCF6172.jpg",
  "albums/uk/full/DSCF6209.jpg",
  "albums/uk/full/DSCF6317.jpg",
  "albums/uk/full/DSCF6328.jpg",
  "albums/uk/full/DSCF6491.jpg",
  "albums/uk/full/DSCF6524.jpg",
  "albums/uk/full/DSCF6550.jpg",
  "albums/uk/full/DSCF6642.jpg",
  "albums/uk/full/DSCF6729.jpg",
  "albums/uk/full/DSCF6756.jpg",
  "albums/uk/full/DSCF6775.jpg",
  "albums/uk/full/DSCF6908.jpg",
  "albums/uk/full/DSCF6960.jpg",
  "albums/uk/full/DSCF7083.jpg",
  "albums/uk/full/DSCF7582.jpg",
  "albums/uk/full/DSCF8020.JPG",
  "albums/uk/full/DSCF8039.JPG",
  "albums/uk/full/DSCF8056.jpg",
  "albums/uk/full/DSCF8312.JPG",
  "albums/uk/full/DSCF8514.JPG",
  "albums/uk/full/DSCF8687.JPG",
  "albums/uk/full/DSCF8826.jpg",
];
var info_uk = [
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
  [' ', ' '],
];
Album uk =
    Album(photoPath_uk, photoFullPath_uk, info_uk, 'uk', 'uk', 'uk', 'uk');
