import 'package:flutter/material.dart';
import 'album.dart';
var photoPath_huweitrain = [ 
"albums/huweitrain/DSCF4582.jpg",
"albums/huweitrain/DSCF4585.jpg",
"albums/huweitrain/DSCF4586.jpg",
"albums/huweitrain/DSCF4588.jpg",
"albums/huweitrain/DSCF4591.jpg",
"albums/huweitrain/DSCF4597.jpg",
"albums/huweitrain/DSCF4600.jpg",
"albums/huweitrain/DSCF4603.jpg",
"albums/huweitrain/DSCF4608.jpg",
"albums/huweitrain/DSCF4609.jpg",
"albums/huweitrain/DSCF4615 1.jpg",
"albums/huweitrain/DSCF4615.jpg",
"albums/huweitrain/DSCF4616.jpg",
"albums/huweitrain/DSCF4617.jpg",
"albums/huweitrain/DSCF4620.jpg",
"albums/huweitrain/DSCF4621.jpg",
"albums/huweitrain/DSCF4623.jpg",
"albums/huweitrain/DSCF4625.jpg",
"albums/huweitrain/DSCF4627.jpg",
];
var photoFullPath_huweitrain = [ 
"albums/huweitrain/full/DSCF4582.jpg",
"albums/huweitrain/full/DSCF4585.jpg",
"albums/huweitrain/full/DSCF4586.jpg",
"albums/huweitrain/full/DSCF4588.jpg",
"albums/huweitrain/full/DSCF4591.jpg",
"albums/huweitrain/full/DSCF4597.jpg",
"albums/huweitrain/full/DSCF4600.jpg",
"albums/huweitrain/full/DSCF4603.jpg",
"albums/huweitrain/full/DSCF4608.jpg",
"albums/huweitrain/full/DSCF4609.jpg",
"albums/huweitrain/full/DSCF4615 1.jpg",
"albums/huweitrain/full/DSCF4615.jpg",
"albums/huweitrain/full/DSCF4616.jpg",
"albums/huweitrain/full/DSCF4617.jpg",
"albums/huweitrain/full/DSCF4620.jpg",
"albums/huweitrain/full/DSCF4621.jpg",
"albums/huweitrain/full/DSCF4623.jpg",
"albums/huweitrain/full/DSCF4625.jpg",
"albums/huweitrain/full/DSCF4627.jpg",
];
var info_huweitrain = [ 
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
[ ' ', ' ' ],
];
Album huweitrain = Album(photoPath_huweitrain, photoFullPath_huweitrain, info_huweitrain, 'huweitrain', 'huweitrain', 'huweitrain', 'huweitrain');
