import 'package:flutter/material.dart';
import 'album.dart';

Album ntuclose = Album([
  'albums/ntuclose/_DSF1221.jpg',
  'albums/ntuclose/_DSF1229.jpg',
  'albums/ntuclose/_DSF1278.jpg',
  'albums/ntuclose/_DSF1295.jpg',
  'albums/ntuclose/_DSF1301.jpg',
  'albums/ntuclose/_DSF1346.jpg',
  'albums/ntuclose/_DSF1427.jpg',
  'albums/ntuclose/_DSF1429.jpg',
  'albums/ntuclose/_DSF1435.jpg',
  'albums/ntuclose/_DSF1442.jpg',
  'albums/ntuclose/_DSF1451.jpg',
  'albums/ntuclose/_DSF1474.jpg',
  'albums/ntuclose/_DSF1493.jpg',
  'albums/ntuclose/_DSF1522.jpg',
  'albums/ntuclose/_DSF1561.jpg',
  'albums/ntuclose/_DSF1564.jpg',
  'albums/ntuclose/_DSF1567.jpg',
  'albums/ntuclose/_DSF1606.jpg',
  'albums/ntuclose/_DSF1673.jpg',
  'albums/ntuclose/_DSF1681.jpg',
  'albums/ntuclose/_DSF1685.jpg',
  'albums/ntuclose/_DSF1713.jpg',
  'albums/ntuclose/_DSF1733.jpg',
  'albums/ntuclose/_DSF1745.jpg',
  'albums/ntuclose/_DSF1780.jpg',
  'albums/ntuclose/_DSF1793.jpg',
  'albums/ntuclose/_DSF1806.jpg',
  'albums/ntuclose/_DSF1812.jpg',
  'albums/ntuclose/_DSF1830.jpg',
  'albums/ntuclose/_DSF1834.jpg',
  'albums/ntuclose/_DSF1843.jpg',
  'albums/ntuclose/PXL_20210526_083343341.MP.jpg',
  'albums/ntuclose/_DSF1854.jpg',
  'albums/ntuclose/_DSF1866.jpg',
  'albums/ntuclose/_DSF1875.jpg',
  'albums/ntuclose/_DSF1880.jpg',
  'albums/ntuclose/_DSF1883.jpg'
], [
  'albums/ntuclose/full/_DSF1221.jpg',
  'albums/ntuclose/full/_DSF1229.jpg',
  'albums/ntuclose/full/_DSF1278.jpg',
  'albums/ntuclose/full/_DSF1295.jpg',
  'albums/ntuclose/full/_DSF1301.jpg',
  'albums/ntuclose/full/_DSF1346.jpg',
  'albums/ntuclose/full/_DSF1427.jpg',
  'albums/ntuclose/full/_DSF1429.jpg',
  'albums/ntuclose/full/_DSF1435.jpg',
  'albums/ntuclose/full/_DSF1442.jpg',
  'albums/ntuclose/full/_DSF1451.jpg',
  'albums/ntuclose/full/_DSF1474.jpg',
  'albums/ntuclose/full/_DSF1493.jpg',
  'albums/ntuclose/full/_DSF1522.jpg',
  'albums/ntuclose/full/_DSF1561.jpg',
  'albums/ntuclose/full/_DSF1564.jpg',
  'albums/ntuclose/full/_DSF1567.jpg',
  'albums/ntuclose/full/_DSF1606.jpg',
  'albums/ntuclose/full/_DSF1673.jpg',
  'albums/ntuclose/full/_DSF1681.jpg',
  'albums/ntuclose/full/_DSF1685.jpg',
  'albums/ntuclose/full/_DSF1713.jpg',
  'albums/ntuclose/full/_DSF1733.jpg',
  'albums/ntuclose/full/_DSF1745.jpg',
  'albums/ntuclose/full/_DSF1780.jpg',
  'albums/ntuclose/full/_DSF1793.jpg',
  'albums/ntuclose/full/_DSF1806.jpg',
  'albums/ntuclose/full/_DSF1812.jpg',
  'albums/ntuclose/full/_DSF1830.jpg',
  'albums/ntuclose/full/_DSF1834.jpg',
  'albums/ntuclose/full/_DSF1843.jpg',
  'albums/ntuclose/PXL_20210526_083343341.MP.jpg',
  'albums/ntuclose/full/_DSF1854.jpg',
  'albums/ntuclose/full/_DSF1866.jpg',
  'albums/ntuclose/full/_DSF1875.jpg',
  'albums/ntuclose/full/_DSF1880.jpg',
  'albums/ntuclose/full/_DSF1883.jpg'
], [
  ['舟山路口', '1/250, f/5.6, FUJIFILM X-T2'],
  ['舟山路口', '1/500, f/5.6, FUJIFILM X-T2'],
  ['社會科學院圖書館', '1/40, f/7.1, FUJIFILM X-T2'],
  ['118巷，巧味快餐', '1/40, f/9, FUJIFILM X-T2'],
  ['118巷，水果攤', '1/40, f/7.1, FUJIFILM X-T2'],
  ['籃球場', '1/3200, f/3.6, FUJIFILM X-T2'],
  ['溫州街，笠原麵食館', '1/250, f/4.5, FUJIFILM X-T2'],
  ['普通教學館', '1/250, f/5.6, FUJIFILM X-T2'],
  ['普通教學館', '1/250, f/5.6, FUJIFILM X-T2'],
  ['小福廣場', '1/320, f/4, FUJIFILM X-T2'],
  ['博雅教學館', '1/250, f/4.5, FUJIFILM X-T2'],
  ['博雅教學館', '1/40, f/4, FUJIFILM X-T2'],
  ['農業綜合館', '1/80, f/4.5, FUJIFILM X-T2'],
  ['臺大正門口', '1/30, f/4, FUJIFILM X-T2'],
  ['臺大正門口', '1/30, f/4, FUJIFILM X-T2'],
  ['捷運公館站', '1/30, f/2.8, FUJIFILM X-T2'],
  ['總圖書館臨時窗口', '1/125, f/3.2, FUJIFILM X-T2'],
  ['第一學生活動中心', '1/60, f/5.6, FUJIFILM X-T2'],
  ['第一學生活動中心', '1/125, f/5.6, FUJIFILM X-T2'],
  ['總圖書館', '1/60, f/5.6, FUJIFILM X-T2'],
  ['總圖書館', '1/125, f/5, FUJIFILM X-T2'],
  ['男一宿舍', '1/125, f/5.6, FUJIFILM X-T2'],
  ['男一宿舍', '1/125, f/5.6, FUJIFILM X-T2'],
  ['辛亥路，萬才館，國青大樓', '1/250, f/5.6, FUJIFILM X-T2'],
  ['生機系，知武館', '1/125, f/5.6, FUJIFILM X-T2'],
  ['生機系，生機館', '1/320, f/4, FUJIFILM X-T2'],
  ['卓聯大樓，7-11', '1/25, f/3.6, FUJIFILM X-T2'],
  ['管理學院二號館，停車場', '1/160, f/4, FUJIFILM X-T2'],
  ['水源市場', '1/50, f/4.5, FUJIFILM X-T2'],
  ['水源市場', '1/25, f/4.5, FUJIFILM X-T2'],
  ['水源市場', '1/30, f/4.5, FUJIFILM X-T2'],
  ['公館，全家便利商店', '1/125, f/1.8, Google Pixel 3'],
  ['小小福用餐區', '1/125, f/5.6, FUJIFILM X-T2'],
  ['水源市場', '1/125, f/8, FUJIFILM X-T2'],
  ['公館，鴉片粉圓', '1/125, f/8, FUJIFILM X-T2'],
  ['捷運公館站，一號出口', '1/125, f/8, FUJIFILM X-T2'],
  ['社會科學院', '1/125, f/8, FUJIFILM X-T2'],
], '#上學計畫', 'The GoToSchool Project', "臺大封校影像紀錄",
    '2021年5月，新冠肺炎在臺灣重新肆虐，\n臺大宣布該學期全面遠距教學，\n所有同學不必再到學校上課。\n這系列影像希望呈現出空無一人的校園，\n如何在疫情之下守護所有同學的安全，展現韌性與堅毅。');

class NtuClose extends StatelessWidget {
  const NtuClose({
    Key? key,
    required this.textStyle_albumTitle,
    required this.textStyle_albumSubtitle,
  }) : super(key: key);

  final TextStyle textStyle_albumTitle;
  final TextStyle textStyle_albumSubtitle;

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: EdgeInsets.all(8),
      width: MediaQuery.of(context).size.width * 0.6,
      height: MediaQuery.of(context).size.height * 0.8,
      decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20),
          border: Border.all(color: Colors.blueGrey.shade500, width: 10),
          image: DecorationImage(
            image: ntuclose.photosList[14].image,
            fit: BoxFit.contain,
            alignment: Alignment.bottomRight,
          )),
      child: Column(
        mainAxisSize: MainAxisSize.max,
        children: [
          Align(
            alignment: Alignment.topLeft,
            child: Padding(
              padding: EdgeInsets.all(20),
              child: Text('NTU\nUnder Covid', style: textStyle_albumTitle),
            ),
          ),
          Align(
            alignment: Alignment.topLeft,
            child: Padding(
              padding: EdgeInsets.symmetric(horizontal: 20),
              child: Text('#上學計畫: 臺大封校的疫情紀實', style: textStyle_albumSubtitle),
            ),
          ),
        ],
      ),
    );
  }
}
