import 'package:flutter/material.dart';
import 'album.dart';

Album penghu = Album([
  'albums/penghu/_DSF0709.jpg',
  'albums/penghu/_DSF0711.jpg',
  'albums/penghu/_DSF0713.jpg',
  'albums/penghu/_DSF0714.jpg',
  'albums/penghu/_DSF0715.jpg',
  'albums/penghu/_DSF0729.jpg',
  'albums/penghu/_DSF0738.jpg',
  'albums/penghu/_DSF0739.jpg',
  'albums/penghu/_DSF0758.jpg',
  'albums/penghu/_DSF0771.jpg',
  'albums/penghu/_DSF0779.jpg',
  'albums/penghu/_DSF0793.jpg',
  'albums/penghu/_DSF0826.jpg',
  'albums/penghu/_DSF0834.jpg',
  'albums/penghu/_DSF0923.jpg',
  'albums/penghu/_DSF0985.jpg',
  'albums/penghu/_DSF1003.jpg',
  'albums/penghu/_DSF1011.jpg',
  'albums/penghu/_DSF1013.jpg',
  'albums/penghu/_DSF1040.jpg',
  'albums/penghu/_DSF1047.jpg',
  'albums/penghu/_DSF1064.jpg',
  'albums/penghu/_DSF1070.jpg',
  'albums/penghu/_DSF1072.jpg',
  'albums/penghu/_DSF1074.jpg',
  'albums/penghu/_DSF1085.jpg',
  'albums/penghu/_DSF1090.jpg',
  'albums/penghu/_DSF1099.jpg',
  'albums/penghu/_DSF1123.jpg',
  'albums/penghu/_DSF1125.jpg',
  'albums/penghu/_DSF1149.jpg',
  'albums/penghu/_DSF1153.jpg',
  'albums/penghu/_DSF1172.jpg',
  'albums/penghu/_DSF1181.jpg'
], [
  'albums/penghu/full/_DSF0709.jpg',
  'albums/penghu/full/_DSF0711.jpg',
  'albums/penghu/full/_DSF0713.jpg',
  'albums/penghu/full/_DSF0714.jpg',
  'albums/penghu/full/_DSF0715.jpg',
  'albums/penghu/full/_DSF0729.jpg',
  'albums/penghu/full/_DSF0738.jpg',
  'albums/penghu/full/_DSF0739.jpg',
  'albums/penghu/full/_DSF0758.jpg',
  'albums/penghu/full/_DSF0771.jpg',
  'albums/penghu/full/_DSF0779.jpg',
  'albums/penghu/full/_DSF0793.jpg',
  'albums/penghu/full/_DSF0826.jpg',
  'albums/penghu/full/_DSF0834.jpg',
  'albums/penghu/full/_DSF0923.jpg',
  'albums/penghu/full/_DSF0985.jpg',
  'albums/penghu/full/_DSF1003.jpg',
  'albums/penghu/full/_DSF1011.jpg',
  'albums/penghu/full/_DSF1013.jpg',
  'albums/penghu/full/_DSF1040.jpg',
  'albums/penghu/full/_DSF1047.jpg',
  'albums/penghu/full/_DSF1064.jpg',
  'albums/penghu/full/_DSF1070.jpg',
  'albums/penghu/full/_DSF1072.jpg',
  'albums/penghu/full/_DSF1074.jpg',
  'albums/penghu/full/_DSF1085.jpg',
  'albums/penghu/full/_DSF1090.jpg',
  'albums/penghu/full/_DSF1099.jpg',
  'albums/penghu/full/_DSF1123.jpg',
  'albums/penghu/full/_DSF1125.jpg',
  'albums/penghu/full/_DSF1149.jpg',
  'albums/penghu/full/_DSF1153.jpg',
  'albums/penghu/full/_DSF1172.jpg',
  'albums/penghu/full/_DSF1181.jpg'
], [
  ['舟山路口', 'FUJIFILM X-T2'],
  ['舟山路口', 'FUJIFILM X-T2'],
  ['社會科學院圖書館', 'JIFILM X-T2'],
  ['118巷，水果攤', 'FUJIFILM X-T2'],
  ['籃球場', 'FUJIFILM X-T2'],
  ['溫州街，笠原麵食館', 'FUJIFILM X-T2'],
  ['普通教學館', 'FUJIFILM X-T2'],
  ['普通教學館', 'FUJIFILM X-T2'],
  ['小福廣場', 'FUJIFILM X-T2'],
  ['博雅教學館', 'FUJIFILM X-T2'],
  ['博雅教學館', 'FUJIFILM X-T2'],
  ['農業綜合館', 'FUJIFILM X-T2'],
  ['臺大正門口', 'FUJIFILM X-T2'],
  ['臺大正門口', 'FUJIFILM X-T2'],
  ['捷運公館站', 'FUJIFILM X-T2'],
  ['總圖書館臨時窗口', 'FUJIFILM X-T2'],
  ['第一學生活動中心', 'FUJIFILM X-T2'],
  ['第一學生活動中心', 'FUJIFILM X-T2'],
  ['總圖書館', 'FUJIFILM X-T2'],
  ['總圖書館', 'FUJIFILM X-T2'],
  ['男一宿舍', 'FUJIFILM X-T2'],
  ['男一宿舍', 'FUJIFILM X-T2'],
  ['辛亥路，萬才館，國青大樓', 'FUJIFILM X-T2'],
  ['生機系，知武館', 'FUJIFILM X-T2'],
  ['生機系，生機館', 'FUJIFILM X-T2'],
  ['卓聯大樓，7-11', 'FUJIFILM X-T2'],
  ['管理學院二號館，停車場', 'FUJIFILM X-T2'],
  ['水源市場', 'FUJIFILM X-T2'],
  ['水源市場', 'FUJIFILM X-T2'],
  ['水源市場', 'FUJIFILM X-T2'],
  ['水源市場', 'FUJIFILM X-T2'],
  ['公館，全家便利商店', 'FUJIFILM X-T2'],
  ['水源市場', 'FUJIFILM X-T2'],
]);
